### ISSUE TITLE
Exception: The server was unable to process the request due to an internal error. 

### ISSUE THREAD

**Issue by marcojulioarg** [luisiturrios/python-cfdiclient#12]
Hola, estoy tratando de hacer una descarga de metadata, sin embargo, me sale el error siguiente. Alguna sugerencia?

` from cfdiclient import (
    Autenticacion,
    SolicitaDescarga,
    VerificaSolicitudDescarga,
    DescargaMasiva,
)
from cfdiclient import Fiel

FIEL_KEY = 'data/certs/fiel_key.key'
FIEL_CER = 'data/certs/fiel_cer.cer'
FIEL_PAS = 'XXXXX'
RFC = "XXXXXXXXXXXX"
cer_der = open(FIEL_CER, 'rb').read()
key_der = open(FIEL_KEY, 'rb').read()
fiel = Fiel(cer_der, key_der, FIEL_PAS)

auth = Autenticacion(fiel)

token = auth.obtener_token()

FECHA_INICIAL = datetime.date(2018, 7, 1)
FECHA_FINAL = datetime.date(2018, 7, 20)

descarga = SolicitaDescarga(fiel)

solicitud = descarga.solicitar_descarga(
    token,
    RFC,
    FECHA_INICIAL,
    FECHA_FINAL,
    rfc_receptor=RFC,
    tipo_solicitud='METADATA',
) `

> Exception: The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs.

**Comment by AlanBarreraA** [comment]
¿Has encontrado alguna forma de solucionarlo? tengo el mismo inconveniente

**Comment by luisiturrios** [comment]
El tipo de solicitud esta mal escrito. 

`
TIPO_SOLICITUD = (
    ('CFDI', 'CFDI'),
    ('Metadata', 'Metadata'),
)
`
