### ISSUE TITLE
Duda - Uso de cert y key

### ISSUE THREAD

**Issue by marcojulioarg** [luisiturrios/python-cfdiclient#8]
Si solo necesito los metadatos de las facturas y no todo lo demas, hay alguna manera de solamente utilizar mi email registrado y el password en lugar de usar todo el cert y el key?

**Comment by luisiturrios** [comment]
Para utilizar este método es necesario la Firma vigente.

**Comment by marcojulioarg** [comment]
> 
> 
> Para utilizar este método es necesario la Firma vigente.

Muchas gracias por la pronta respuesta, tengo otra duda si me podrias apoyar. Sabes si hay alguna manera de hacerlo solamente con el emial y contrase;a? O a fuerza necesito la Firma

**Comment by luisiturrios** [comment]
Creo que haciendo HTML scraper sobre el sitio directamente pero puedes  tener problemas con la captcha

**Comment by marcojulioarg** [comment]
> 
> 
> Creo que haciendo HTML scraper sobre el sitio directamente pero puedes tener problemas con la captcha

Muchas gracias, tengo uno de esos con selenium pero queria probar con el webservice pues para eso esta. Me gusto mucho como programaste este modulo, es facil de entender que las otras alternativas. Solo te molesto con una duda mas, si en lugar de usar el cert y el key, puedo usar archivos PFX?
